### DISCUSSION TITLE
Is Pinniped working with unverified e-mails from our OIDC?

### DISCUSSION THREAD

**Discussion by junoriosity** [vmware-tanzu/pinniped#1034] [Q&A] [answered]
I deployed kubeapps with 

```
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-crds.yaml
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-resources.yaml

cat <<EOF | kubectl apply -f -
kind: JWTAuthenticator
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
metadata:
  name: jwt-authenticator
spec:
  issuer: https://my-auth.eu.auth0.com/
  audience: my-client-id
  claims:
    groups: groups
    username: email
EOF

cat <<EOF | kubectl apply -f -
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: test@test.com
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubeapps-operators
EOF

kubectl create ns kubeapps
helm install kubeapps bitnami/kubeapps --namespace kubeapps -f myvals.yaml 
```

where `myvals.yaml` is

```
useHelm3: true
authProxy:
  additionalFlags:
    - --oidc-issuer-url=https://my-domain.eu.auth0.com
    - --insecure-oidc-allow-unverified-email=true
  clientID: my-client-id
  clientSecret: my-client-secret
  cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
  enabled: true
  provider: oidc

pinnipedProxy:
  enabled: true # if using Pinniped, you'll need to enable this option here
#  defaultAuthenticatorType: jwt
#  defaultAuthenticatorName: jwt-authenticator

clusters:
  - name: default
    apiServiceURL: https://... # impersonation proxy URL
    certificateAuthorityData: ... #  impersonation proxy CA
    pinnipedConfig:
      enabled: true
```

Now, when I try to login with a **verified** e-mail address things are usual - and desired.

If I use an **unverified**, however, I am immediately forwarded to the login page

<img width="440" alt="kubeapps_login" src="https://user-images.githubusercontent.com/5286536/155149444-37addf7c-fb42-4ce3-bab1-b4975302b3f2.png">

The logs say the following for pinniped-proxy

```
INFO pinniped_proxy::service > GET https://my-k8s-url/ 401 Unauthorized
ERROR pinniped_proxy::service > Unauthorized by pinniped: authentication failed

Caused by:
authentication failed
```

and the auth-proxy says

```
...
10.244.0.238:46912 - 82bb7643658afb8467e7e5d1c7e8212d - test4@test.com [2022/02/22 13:53:40] kubeapps.my-domain.com GET / "/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 304 0 0.002
10.244.0.238:46912 - 15b1691c72f0417f4d788b879b63d0fc - test4@test.com [2022/02/22 13:53:41] kubeapps.my-domain.com GET / "/custom_locale.json" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 200 2 0.002
10.244.0.238:46912 - 93d859119e308d2c5bcb826f2fc7600d - test4@test.com [2022/02/22 13:53:41] kubeapps.my-domain.com GET / "/custom_style.css" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 200 0 0.004
10.244.0.238:46912 - 86cb93454c5270f4bcbfc748a580ad44 - test4@test.com [2022/02/22 13:53:44] [AuthSuccess] Authenticated via OAuth2: Session{email:test4@test.com user:auth0|6214ead41f466500695785e2 PreferredUsername: token:true id_token:true created:2022-02-22 13:53:44.038554151 +0000 UTC m=+338.782961718 expires:2022-02-23 13:53:44.03808447 +0000 UTC m=+86738.782492059}
10.244.0.238:46912 - 86cb93454c5270f4bcbfc748a580ad44 - - [2022/02/22 13:53:43] kubeapps.my-domain.com GET - "/oauth2/callback?code=PshPsOkmUGlUe4ssiufoiQ6Ta_Aq8ymyjYlUj8w5cTWsl&state=vO8ZXsKyLG3QzZDDOZo4Diyf-S6xtERN9MixbBXu3fo%3A%2F" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 302 24 0.461
10.244.0.238:46912 - 7f6a789e88aa45449575d92846b64bad - - [2022/02/22 13:53:45] kubeapps.my-domain.com GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 302 317 0.000
10.244.0.238:46912 - 54c2d227cc6f79868f1e19eedb78fd0d - test4@test.com [2022/02/22 13:53:46] kubeapps.my-domain.com GET / "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 401 47 0.103
...
```

Do you know whether it is possible to make work with unverified e-mails from Auth0?
