### DISCUSSION TITLE
Change callback URL to something else than localhost for usage at Auth0

### DISCUSSION THREAD

**Discussion by junoriosity** [vmware-tanzu/pinniped#1095] [Q&A]
When I am using a kubeconfig file like

```
apiVersion: v1
kind: Config
current-context: pinniped
clusters:
- cluster:
    certificate-authority-data: LS0tLS[...]
    server: https://my-kubernetes-api-endpoint.example.com:59986
  name: pinniped
contexts:
- context:
    cluster: pinniped
    user: pinniped
  name: pinniped
users:
- name: pinniped
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /usr/local/bin/pinniped
      args:
      - login
      - oidc
      - --enable-concierge
      - --concierge-api-group-suffix=pinniped.dev
      - --concierge-authenticator-name=my-jwt-authenticator
      - --concierge-authenticator-type=jwt
      - --concierge-endpoint=https://my-kubernetes-api-endpoint.example.com:59986
      - --concierge-ca-bundle-data=LS0tLS[...]
      - --issuer=https://my-oidc-issuer.eu.auth0.com/
      - --client-id=my-client-id
      - --scopes=offline_access,openid,email
      - --listen-port=12345
      - --request-audience=my-client-id
 ```

I have to use the callback URI http://127.0.0.1:12345/callback (see here https://pinniped.dev/docs/howto/configure-concierge-jwt/). 

However, my OIDC provider Auth0 explicitly requires me not to use such a callback URI at localhost.

Can I change that somehow?
