### DISCUSSION TITLE
Pinniped ignore kubeconfig with insecure-skip-tls-verify

### DISCUSSION THREAD

**Discussion by HamzaZo** [vmware-tanzu/pinniped#1888] [Q&A]
Hello,

I'm using the latest version of pinniped `v0.28.0` with kubernetes `1.29` and the apiserver of our clusters use self signed certificate (I know it's not good but it's been designed like this, making it difficult to change existing clusters )
Setting `insecure-skip-tls-verify: true ` in the below kubeconfig seems to be ignored by getting the following error:
```
Error: could not complete Concierge credential exchange: could not login: Post"https://apiserver.org:443/apis/login.concierge.pinniped.dev/v1alpha1/tokencredentialrequests" tls : failed to verify certificate: x509 certificate signed by unknown authority 

```

```
apiVersion: v1
clusters:
- cluster: 
      #certificate-authority-data: LS0...
     server: https://apiserver.org:443
     insecure-skip-tls-verify: true 
   name: cluster-1
contexts: 
- context: 
     cluster: cluster-1
     user: k8s
   name: context1
kind:  config
users: 
- name: k8s
  user: 
    exec: 
      apiVersion: client.authentication.k8s.io/v1beta1
     args: 
     - login
     - oidc
     - --enable-concierge
     - ...
     - --concierge-endpoint=https://apiserver.org:443
     - --concierge-ca-bundle-data=LS0...
```

Any idea please how to skip the tls verify ?
