### DISCUSSION TITLE
Connecting to Active Directory via LDAP without encryption

### DISCUSSION THREAD

**Discussion by 1sk0ne** [vmware-tanzu/pinniped#2168] [Q&A] [answered]
Hello, please tell me if it is possible to bypass an LDAP connection without encryption, since I do not have LDAP configured on my domain controllers due to the fact that all traffic is on the internal network. 

As a result, if I get an error with the following data:

```
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: ActiveDirectoryIdentityProvider
metadata:
  name: pinniped-active-directory
  namespace: pinniped-supervisor
spec:
  host: dc-1.base.local:389
  tls:
    certificateAuthorityData: <self-signed-controller-domain-certificate>
```
Logs:
```
{"level":"info","timestamp":"2024-12-27T08:46:10.757059Z","caller":"go.pinniped.dev/internal/controller/supervisorconfig/upstreamwatchers/upstream_watchers.go:143$upstreamwatchers.TestConnection","message":"testing LDAP connection using TLS failed, so trying again with StartTLS","error":"error dialing host \"dc1.base.local:389\": LDAP Result Code 200 \"Network Error\": read tcp 10.140.44.152:41140->10.33.12.13:389: read: connection reset by peer","host":"dc1.base.local:389"}
{"level":"info","timestamp":"2024-12-27T08:46:10.770079Z","caller":"go.pinniped.dev/internal/controller/supervisorconfig/upstreamwatchers/upstream_watchers.go:154$upstreamwatchers.TestConnection","message":"testing LDAP connection using StartTLS also failed","error":"error dialing host \"dc1.base.local:389\": LDAP Result Code 200 \"Network Error\": read tcp 10.140.44.15:41140->10.33.12.1:389: read: connection reset by peer","host":"dc1.base.local:389"}
```

I would also like to know if it is possible to use a connection specifying base.local:389 
So, if a particular domain controller fails, is it possible to connect to the next one?
