### ISSUE TITLE
Use go 1.19's soft memory limit when it is released

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#1103]
https://github.com/golang/go/issues/48409 is expected to release in go 1.19 and will allow us to do something like `deployment.spec.podTemplate.spec.containers[0]`:

```yaml
      env:
       # reduce OOM likelyhood
       - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: <name>
              resource: limits.memory
```
