### ISSUE TITLE
configure group authorization in concierge JWTauthenticator with on-prem gitlab failed to work

### ISSUE THREAD

**Issue by hsiaand** [vmware-tanzu/pinniped#1275]
**What happened?**

> Please be specific and include screenshots and logs!
created JWTauthenticator with following
```
kubectl apply -n pinniped-concierge -f-<<EOD
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: gitlab
spec:
  issuer: https://gitlab.company.com
  audience: 93a4193c6XXXXXXXXXXXXXXX
  claims:
    username: email
    groups: groups
EOD
```

then create kube-config
```
pinniped get kubeconfig --oidc-scopes openid,email --oidc-client-id 93a4193c6XXXXXXXXXXXXXXX  > ~/.kube/gitlab.yaml
```

when running 
```
export KUBECONFIG=~/.kube/gitlab.yaml

pinniped whoami
Log in by visiting this link:

    https://gitlab.company.com/oauth/authorize?access_type=offline&client_id=93a4193c6XXXXXXXXXXXXXXX&code_challenge=b73CD3v7N4i4oEiATQbeIfQrlLEyv-z8wqun5V5BQkc&code_challenge_method=S256&nonce=226aed34bffe1a8fe3dee915493e088b&redirect_uri=http%3A%2F%2F127.0.0.1%3A65207%2Fcallback&response_type=code&scope=email+openid&state=b33f40629f891753727654b4cf635401

Current cluster info:

Name: kubernetes-pinniped
URL: https://10.100.17.77:6443

Current user info:

Username: first.last@company.com
Groups: system:authenticated
```

inspect the content of ~/.config/pinniped/sessions.yaml, it does include the project name as group in array
```
      claims:
        aud: 93a4193c6XXXXXXXXXXXXXXX
        auth_time: 1661440688
        email: first.last@company.com
        email_verified: true
        exp: 1662035776
        groups:
        - project1
        - project2
        
```

**What did you expect to happen?**
groups should appear in the pinniped whoami so I can use that for cluster role binding

> Please be specific and include proposed behavior!

**What is the simplest way to reproduce this behavior?**

**In what environment did you see this bug?**
- Pinniped server version:  v0.19.0
- Pinniped client version: v0.19.0
- Pinniped container image (if using a public container image): projects.registry.vmware.com/pinniped/pinniped-server:v0.19.0@sha256:f71d3b973ba111a7b4499a279bf8cdf716e675ab0510645df25969fb2366b209
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): on-prem gitlab
- Kubernetes version (use `kubectl version`):  ```Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.6```
- Kubernetes installer & version (e.g., `kubeadm version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**
