### ISSUE TITLE
Superfluous error logs when only `ImpersonationProxy` strategy is available

### ISSUE THREAD

**Issue by peterbuecker-form3** [vmware-tanzu/pinniped#1370]
**Is your feature request related to a problem? Please describe.**

When running Pinniped Concierge in a managed Kubernetes cluster like EKS, it regularly logs error messages stating that it can't find any `kube-controller-manager` pods, although it has been configured to always run in `ImpersonationProxy` mode:

```
{"level":"error","timestamp":"2023-01-17T15:20:13.935196Z","caller":"go.pinniped.dev/internal/controllerlib/controller.go:219$controllerlib.(*controller).handleKey","message":"kube-cert-agent-controller: { } failed with: could not find a healthy kube-controller-manager pod (0 candidates)\n"}
```

The `CredentialIssuer` in use:

```yaml
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  labels:
    app: pinniped-concierge
  name: pinniped-concierge-config
spec:
  impersonationProxy:
    mode: enabled
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
      type: LoadBalancer
status:
  strategies:
    - lastUpdateTime: "2023-01-16T09:13:21Z"
      message: could not find a healthy kube-controller-manager pod (0 candidates)
      reason: CouldNotFetchKey
      status: Error
      type: KubeClusterSigningCertificate
    - frontend:
        impersonationProxyInfo:
          certificateAuthorityData: LS0tLS1CRUdJTiB...
          endpoint: https://...
        type: ImpersonationProxy
      lastUpdateTime: "2023-01-16T09:13:27Z"
      message: impersonation proxy is ready to accept client connections
      reason: Listening
      status: Success
      type: ImpersonationProxy
```

**Describe the solution you'd like**

When `ImpersonationProxy` has been selected, and it's working correctly, I don't expect to see any `error` logs from Concierge relating to `KubeClusterSigningCertificate` mode.

**Describe alternatives you've considered**

Alternatively, the log level of these messages could be reduced from `error` to `debug`.

**Are you considering submitting a PR for this feature?**

Yes, I'd be happy to send a PR for this if you find it a reasonable improvement and it seems like a relatively simple change to do for a newcomer to this project.

**Additional context**

None.
