### ISSUE TITLE
Kubernetes creates thousands of failed kube-cert-agent pods under certain conditions

### ISSUE THREAD

**Issue by cfryanr** [vmware-tanzu/pinniped#1507]
**What happened?**

The Pinniped Concierge controller which automatically creates the kube-cert-agent Deployment on clusters where the control plane nodes are visible in the k8s API, will choose a control plane node and use `nodeName: control-plane-node-name` in the pod template spec of the Deployment. This is because it wants that pod to run on a control plane node and it wants to copy the same volume mounts that the control plane is using onto the new pod.

This generally works fine. However, when the selected control plane node does not have enough cpu or memory capacity to schedule the pod based on the pod's requested cpu and memory (which is tiny but non-zero), then Kubernetes does something unexpected. The pod is created, it fails to be scheduled due to `OutOfcpu`, and then Kubernetes immediately tries again with no backoff. Within minutes, there are thousands of failed pods (at a rate of ~1000 pods created per ~7 minutes). Kubernetes does not clean up these pods either.

This strange behavior of Kubernetes can be seen outside of the context of Pinniped as well. On a Kind cluster, create this Deployment to see the exact same behavior:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      test-deploy: v1
  template:
    metadata:
      labels:
        test-deploy: v1
    spec:
      nodeName: kind-control-plane # this is the name of a control plane node on the cluster
      containers:
        - name: sleeper
          image: debian:stable-slim
          imagePullPolicy: IfNotPresent
          command: [ sleep, infinity ]
          resources:
            requests:
              cpu: 8000m # this is more than is available on the control plane node at the time of deployment
```

Immediately there will be many many pods created, and they are not cleaned up automatically. (When the Deployment is deleted, then all pods are also deleted.)

**What did you expect to happen?**

I would expect a more graceful failure mode for the kube-cert-agent Deployment where Kubernetes does not create thousands of dead pods when there is not enough capacity on the control plane node.

According to this related issue in the Kubernetes repo (see https://github.com/kubernetes/kubernetes/issues/113907#issuecomment-1427549938 and https://github.com/kubernetes/kubernetes/issues/113907#issuecomment-1429861202):
> If you want to target a specific node and wait until the node has resources, a nodeSelector or node affinity that selects only the desired node is the way to accomplish that.

Perhaps the Pinniped Concierge should not use the `nodeName` setting on the Deployment, but should use a different method to select the control plane node. If there is another method to select the node which does not trigger this strange behavior of Kubernetes, then that would be preferred. It would be better for the pod to get stuck in `Pending` state when it cannot be scheduled due to a lack of resources than to create thousands of pods.

**What else is there to know about this bug?**

Any potential fix would need to consider upgrades. The kube-cert-agent Deployment may already exist on the cluster during an upgrade. The Pinniped Concierge controller would need to gracefully handle that case by updating the Deployment, or by deleting/recreating the Deployment if it needs to change any read-only fields of the Deployment as part of this solution.

The Kube cert agent controller, which creates the deployment, is currently using the following business logic:
1. Out of all healthy controller manager pods (pods with label `"component": "kube-controller-manager"` in the `kube-system`, pick the one with the newest `CreationTimestamp`.
2. On the new Deployment, copy the `NodeSelector`, `NodeName`, `Tolerations` (and some other stuff) from the pod chosen in the previous step, in an effort to cause the kube cert agent pod to get scheduled onto the same node as the pod from the previous step. Also copy its `Volumes` and `VolumeMounts` so the new pod can read the same files.
3. The problem seems to be that the `NodeSelector` is empty and the `NodeName` is not, so we end up accidentally side-stepping the Kubernetes pod scheduler for the new pod.

See https://github.com/vmware-tanzu/pinniped/blob/v0.23.0/internal/controller/kubecertagent/kubecertagent.go#L558-L562. Is there some way that we could maybe use a `NodeSelector` or node affinity and still be sure that the new pod will be able to mount the same volumes?

**Comment by cfryanr** [comment]
What would happen if the kube-cert-agent deployment did not make any cpu or memory requests? Would it always get placed onto the requested node, even when that node has no available CPU or memory? Could that perhaps be a workaround? What would be the downsides of not being in the guaranteed QoS tier anymore? Would the kube cert agent controller need to handle this in a special way during upgrade, or are the CPU and memory requests editable on a Deployment?

**Comment by cfryanr** [comment]
Confirmed on a kind cluster that using `nodeName` to place the pod onto a node which has its CPU 100% requested does not trigger this bug when the pod makes no CPU request.

```yaml
# Deployed this onto a Kind cluster with a single node.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      test-deploy: v1
  template:
    metadata:
      labels:
        test-deploy: v1
    spec:
      containers:
        - name: sleeper
          image: debian:stable-slim
          imagePullPolicy: IfNotPresent
          command: [ sleep, infinity ]
          resources:
            requests:
              # This is the exact amount of CPU remaining on my
              # cluster's node, causing it to be 100% requested
              # after this pod is scheduled.
              cpu: 7050m

# After the above deployment was finished, then deployed this successfully.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy-with-nodename
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      test-deploy-with-nodename: v1
  template:
    metadata:
      labels:
        test-deploy-with-nodename: v1
    spec:
      # This is the name of the node on my cluster.
      nodeName: pinniped-control-plane
      containers:
        - name: sleeper
          image: debian:stable-slim
          imagePullPolicy: IfNotPresent
          command: [ sleep, infinity ]
          # Note that there is no resources requests/limits here.
          # The pod is started successfully despite the node's
          # CPU already being 100% requested before this
          # deployment starts.
```
