### ISSUE TITLE
Feature Request: Configurable Expiration Time for Client Certificate

### ISSUE THREAD

**Issue by uozalp** [vmware-tanzu/pinniped#1987]
**Is your feature request related to a problem? Please describe.**
We use K9s for all our administration tasks. Every 5 minutes, K9s loses connection to our cluster. We have determined that this issue is due to our client certificate credential expiring. After 10-30 seconds, a new 10-minute certificate is issued (valid from 5 minutes in the past), and the K9s connection is restored.

```
apiVersion: config.supervisor.pinniped.dev/v1alpha1
credentials:
- creationTimestamp: "2024-06-12T11:34:38Z"
  credential:
    clientCertificateData: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    clientKeyData: |
      -----BEGIN PRIVATE KEY-----
      -----END PRIVATE KEY-----
    expirationTimestamp: "2024-06-12T11:39:41Z"
  key: 0c599d95e49704e...
  lastUsedTimestamp: "2024-06-12T11:34:38Z"
kind: CredentialCache
```
We noticed that the 5-minute expiration time is hardcoded in the source code: [Link to Source Code](https://github.com/vmware-tanzu/pinniped/blob/80e1fee20873050169bc89733e56a2e61704b4fc/internal/registry/credentialrequest/rest.go#L28).

**Describe the solution you'd like**
We would like this expiration time to be configurable, allowing users to set a custom expiration duration according to their needs.

**Describe alternatives you've considered**
We have not found any alternative solutions. Increasing the default value is not desirable due to security concerns.

![k9s](https://github.com/vmware-tanzu/pinniped/assets/54961032/b8933913-a100-4c02-b9e0-6b6ead93395d)

**Additional context**

Just to clarify, we do not see the issue every 5 minutes. However, if you navigate around in the K9s interface around the time the client certificate expires, you will most likely see the issue.
