### ISSUE TITLE
Allow claim mapping expressions in JWT Authenticator

### ISSUE THREAD

**Issue by rickhlx** [vmware-tanzu/pinniped#2340]
**Is your feature request related to a problem? Please describe.**

When obtaining claims to identify users, there might be instances where a custom string built from claims or validating claims based on information obtained would be useful.

**Describe the solution you'd like**

When obtaining claims from JWT, it's useful to evaluate a claim mapping built from claims received. For example, validating if a user's email has been verified:

The expression:

```cel
claims.email_verified == true ? claims.email : null
```

The claims:

```yaml
claims:
    email: hello@world.com
    email_verified: true
```

The result would be

```
hello@world.com
```

**Describe alternatives you've considered**

Alternatives would be to have the `sub` or other claims built dynamically from the issuer, however this is not always feasible.

**Are you considering submitting a PR for this feature?**

- **How will this project improvement be tested?**
- **How does this change the current architecture?**
- **How will this change be backwards compatible?**
- **How will this feature be documented?**

**Additional context**

**Comment by cfryanr** [comment]
Hi @rickhlx, thanks for creating this issue!

I see that you used `email_verified` as your example. I thought I would just point out that if you are using the Pinniped Supervisor then it has special handling for the `email` and `email_verified` claims to ensure that if the `email_verified` claim is present, and if the username will come from the `email` claim, then the value of `email_verified` must be `true`. That would happen during login, before any token is passed to the JWTAuthenticator. If you're not using the Pinniped Supervisor, then that wouldn't help, of course.

Is `email_verified` your primary use case for this feature, or did you have other reasons to need it?

Theoretically, the JWTAuthenticator could support the same features as Kubernetes JWT Authentication. It would just be work to expose the configuration options, validate them, dynamically read/re-read them as they change, etc.

**Comment by rickhlx** [comment]
That was just an example, my specific use case is that I'm using an ID token generated from GitLab CI/CD which includes the `ref_protected=true|false` claim. I want to use that claim to dynamically configure the `username` claim, allowing me to have different RBAC for protected vs. non-protected branches.

**Comment by rickhlx** [comment]
@cfryanr juat following up, is this a feature you'd consider for the project? If so I'd be willing to submit a PR for the feature.

**Comment by rickhlx** [comment]
@cfryanr happy to report back this is working beautifully for us. 

We're now able to build our claim from GitLab OIDC tokens. 

```
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: jwt-authenticator-gitlab
spec:
  audience: foo
  claims:
    usernameExpression: '"gitlab:" + claims.project_path + ":" + (claims.ref_protected == "true" ? "protected" : "unprotected")'
  issuer: https://foobar.org

```
