### ISSUE TITLE
CA bundle missing from pinniped cli generated kubeconfig when using minikube

### ISSUE THREAD

**Issue by danjahner** [vmware-tanzu/pinniped#251]
**What happened?**

When following the [installation demo](https://github.com/vmware-tanzu/pinniped/blob/main/doc/demo.md) on minikube, everything installs correctly and runs, but when using the generated kubeconfig, it throws an unknown authority error. 

When I look at the generated kubeconfig, the `PINNIPED_CA_BUNDLE` env var is an empty string. Adding the correct CA pem to the kubeconfig resolves the unknown authority error. 

**What did you expect to happen?**

`PINNIPED_CA_BUNDLE` should be populated automatically with `pinniped get-kubeconfig`

**What is the simplest way to reproduce this behavior?**

Start a minikube cluster and walk through the installation demo steps. 

**In what environment did you see this bug?**
- Pinniped server version: v0.2.0
- Pinniped client version: v0.2.0
- Kubernetes version (use `kubectl version`): v1.19.4
- Kubernetes installer & version (e.g., `kubeadm version`): minikube v1.15.1

**Comment by ankeesler** [comment]
I think this has been fixed with the introduction of the new `pinniped get kubeconfig` command in `v0.3.0`.

I followed the Concierge-only demo (https://pinniped.dev/docs/concierge-only-demo/) and after I ran the `pinniped get kubeconfig` step, I saw a CA bundle in my kubeconfig:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ERXhNekUwTlRnMU5Wb1hEVE14TURFeE1URTBOVGcxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2UxCkNRakRRbmxNV3NYWGJmRmRZc3gza1ZtYlpDdithYUxYajBkc090c0NySzFXN1l6ckhIUmlSWWRWSzIvekNaazUKQnVKbmN3S0pWZ1Bqc09OWGhidnpKZlIzL2c1cGJ4T2dBSFIrNldUNkoycXlZa1k0RnZ4Q2sycENCOGQwcUphMQozUjh6NGorb0VoWFpHYm1vNmNKVkkxSjN4c01qL2RrUGFBUnJ3aGxsMmJGRUFoTVRySkZQRlBlOU93WGluckM3CnNRaHVDTk1lSDJtWGgvbUhhVkpJazVxSmRtaGFSNXF2MjBBS2ttaG9MSTV3endzRDNJQUZBamU0WEhzVVhUQjAKTys2VklIMDVnc0x5VWJiRE5yUjdzdWtEb2x5ZDZIVEgwd2E3WUhXU0RoaFREMnIzNDVveEFwTitUOVcyb3JoVgpPUlRYbU9HanVPTS85L0RUU3FVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBU3U3eGNkQU1tT3V2blp6WEZHa3JuY0NYU2RNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCdndJRUxseEdsZVZGdFh6dW5PT1FRcmJOZVhmZWYzNmZXQkUvVEttVDVnMnNKN1pOYQorQTdiU0todzA4Z0ZOWk0zUWovWW1UZnArQ2ZXSTVNWUhUdDhWS1NCTlhVTExzUDI5dExvZkV2S0FsL1g1d0NOCnA3WVJFK2RTWTlmd2gzbHJLeFV4bURJUzQrMzhGK1NuTVJJcUdxVS9Jc0lRZjdDZ00rWXBvM1lpMTg5VEROK2gKazRNZDlpR2NPRzk1RDdHU3UwdXNvUFZkMTNLZGE2ZkYxNkREK05NY2Z0ZCtpYWhwTWJpbkNuWHRCbmtCSGlaVQp6alpFZFJPanNFUEtHMVRkZVVJZGtWdGZkS1htSXorMjd1L25uYnRhQTVXSVordzRNSDZwMXo0TUpycEx6UlFlCmFLMG9GYThCUnVSSGxFRDQyMDRJWjh5ZkVNL05Fb2ZWY3BncAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:49922
  name: pinniped
contexts:
- context:
    cluster: pinniped
    user: pinniped
  name: pinniped
current-context: pinniped
kind: Config
preferences: {}
users:
- name: pinniped
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - static
      - --enable-concierge
      - --concierge-namespace=pinniped-concierge
      - --concierge-authenticator-name=local-user-authenticator
      - --concierge-authenticator-type=webhook
      - --concierge-endpoint=https://127.0.0.1:49922
      - --concierge-ca-bundle-data=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ERXhNekUwTlRnMU5Wb1hEVE14TURFeE1URTBOVGcxTlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2UxCkNRakRRbmxNV3NYWGJmRmRZc3gza1ZtYlpDdithYUxYajBkc090c0NySzFXN1l6ckhIUmlSWWRWSzIvekNaazUKQnVKbmN3S0pWZ1Bqc09OWGhidnpKZlIzL2c1cGJ4T2dBSFIrNldUNkoycXlZa1k0RnZ4Q2sycENCOGQwcUphMQozUjh6NGorb0VoWFpHYm1vNmNKVkkxSjN4c01qL2RrUGFBUnJ3aGxsMmJGRUFoTVRySkZQRlBlOU93WGluckM3CnNRaHVDTk1lSDJtWGgvbUhhVkpJazVxSmRtaGFSNXF2MjBBS2ttaG9MSTV3endzRDNJQUZBamU0WEhzVVhUQjAKTys2VklIMDVnc0x5VWJiRE5yUjdzdWtEb2x5ZDZIVEgwd2E3WUhXU0RoaFREMnIzNDVveEFwTitUOVcyb3JoVgpPUlRYbU9HanVPTS85L0RUU3FVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBU3U3eGNkQU1tT3V2blp6WEZHa3JuY0NYU2RNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCdndJRUxseEdsZVZGdFh6dW5PT1FRcmJOZVhmZWYzNmZXQkUvVEttVDVnMnNKN1pOYQorQTdiU0todzA4Z0ZOWk0zUWovWW1UZnArQ2ZXSTVNWUhUdDhWS1NCTlhVTExzUDI5dExvZkV2S0FsL1g1d0NOCnA3WVJFK2RTWTlmd2gzbHJLeFV4bURJUzQrMzhGK1NuTVJJcUdxVS9Jc0lRZjdDZ00rWXBvM1lpMTg5VEROK2gKazRNZDlpR2NPRzk1RDdHU3UwdXNvUFZkMTNLZGE2ZkYxNkREK05NY2Z0ZCtpYWhwTWJpbkNuWHRCbmtCSGlaVQp6alpFZFJPanNFUEtHMVRkZVVJZGtWdGZkS1htSXorMjd1L25uYnRhQTVXSVordzRNSDZwMXo0TUpycEx6UlFlCmFLMG9GYThCUnVSSGxFRDQyMDRJWjh5ZkVNL05Fb2ZWY3BncAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      - --token=pinny-the-seal:password123
      command: /usr/local/bin/pinniped
      env: []
```
