### ISSUE TITLE
Enable configuration of Concierge impersonation proxy via CredentialIssuer API.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#363]
### Acceptance Criteria

```gherkin
Scenario: configure Concierge impersonation proxy via CredentialIssuer API
  Given that I have an managed cluster with the Pinniped concierge installed
    And that I have set up a TLS certificate and trusted certificate authority
    And that I have configured a Kubernetes LoadBalancer service to route to the concierge impersonation proxy port.
  When I update the Pinniped CredentialIssuer with several new spec fields
    And I manually configure a kubeconfig that points at the external endpoint and trusts the CA
    And I run a kubectl command
  Then my command executes as my identity on the cluster
```

### Notes
This is a followup to #339, which extends the minimal impersonation proxy to accept configuration via the CredentialIssuer API.

### API Changes

The CredentialIssuer API will have several new fields:
```yaml
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: concierge-config
  namespace: concierge

spec:
 
  # (new field)
  impersonationProxy:
    # specify the external name that will route to the impersonation proxy port
    # (future) if empty, automatically provision a LoadBalancer service and use its ExternalName
    externalEndpoint: https://my-load-balancer:1234/

    # configure TLS-related settings
    tls:

      # specify the CA that clients should validate with when connecting to the endpoint
      # (future) if empty, generate a CA and persist it in a Secret with some rotation
      certificateAuthorityData: "[...]"

      # specify a secret with type "kubernetes.io/tls" which will be used to serve the endpoint
      # (future) if empty, issue a certificate using the generated CA
      secretName: my-tls-certificate-and-key

status: # [...]
```

This story does not require any new status fields in CredentialIssuer (that will happen in a future story). It also does not require any "automatic" behavior -- it assumes that the external load balancer and TLS certificates are provisioned out-of-band and specified explicitly.
