### ISSUE TITLE
Enable discovery of Concierge impersonation proxy configuration via CredentialIssuer API.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#364]
### Acceptance Criteria

```gherkin
Scenario: observe Concierge impersonation proxy configuration via CredentialIssuer API
  Given that I have an managed cluster with the Pinniped concierge installed
  When I get the CredentialIssuer CRD for my concierge by running `kubectl get credentialissuer [...]`
  Then I can see that my concierge is running in impersonation proxy mode
    And I can use the information from the CredentialIssuer to build a secure, working kubeconfig that targets the impersonation proxy

Scenario: observe Concierge impersonation proxy configuration via CredentialIssuer API
  Given that I have a self-hosted cluster with the Pinniped concierge installed
  When I get the CredentialIssuer CRD for my concierge by running `kubectl get credentialissuer [...]`
  Then I can see that my concierge is not running in impersonation proxy mode
```

### Notes
This is a followup to #339 and #363, which extends the CredentialIssuer API to report status about how the impersonation proxy is configured.

### API Changes

~~The API changes related to this issue are described in https://hackmd.io/X83kynapQgCJm_sDxXLCxg?view.~~ This has changed again after further discussion.

The CredentialIssuer API will have several new fields:

```yaml
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: concierge-config
  namespace: concierge
status:

  # existing fields from TokenCredentialRequest/cert-agent flow.
  kubeConfigInfo:
    certificateAuthorityData: "[...]"
    server: https://1.2.3.4:6443

  # At one point this field was proposed, but we later changed our minds
  # and moved this data into the `strategies` list below.
  #impersonationProxyInfo:
  #  certificateAuthorityData: # [...]
  #  endpoint: https://external-name:1234

  strategies:
  # existing strategy which is expected to fail on many clusters
  - type: KubeClusterSigningCertificate
     status: Error
     reason: CouldNotFetchKey
     message: did not find kube-controller-manager pod(s)
     lastUpdateTime: "2021-01-25T23:50:07Z"
     frontend: # Same format as shown below. This is a new field.

  # new strategy which should eventually succeed as long as sufficient configuration has been provided
  - type: ImpersonationProxy
     status: Success
     reason: Listening
     message: running impersonation proxy on 0.0.0.0:8444
     lastUpdateTime: "2021-01-25T23:50:07Z"
     frontend:
       type: ImpersonationProxy
       impersonationProxyInfo:
         server: https://some-server:some-port
         certificateAuthorityData: some-base64-encoded-pem-data
   ```
