### ISSUE TITLE
Add concierge impersonation proxy support to `pinniped login` CLI commands.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#366]
### Acceptance Criteria

```gherkin
Scenario: use concierge via the `pinniped login` CLI subcommands.
  Given that I have an managed cluster with the Pinniped concierge installed
    And that I have configured the impersonation proxy appropriately
  When I create a kubeconfig which embeds the `pinniped login` command as an ExecCredential with the proper flags
  Then I can use my kubeconfig to run kubectl commands as my user
```

### Notes
This is a followup to #339 and #364. It covers the `pinniped login` subcommands, but not the `pinniped get kubeconfig` subcommand (that will be yet another story).

### CLI Changes

The kubeconfig which invokes the new behavior should look something like below for the `pinniped login static` case, and the `pinniped login oidc` case should be nearly identical as well:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: "..." # CA bundle of concierge impersonation proxy endpoint 
    server: "https://..." # URL of concierge impersonation proxy endpoint
  name: pinniped
contexts:
- context:
    cluster: pinniped
    user: pinniped
  name: pinniped
current-context: pinniped
kind: Config
preferences: {}
users:
- name: pinniped
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - static
      - --enable-concierge
      - --concierge-mode=ImpersonationProxy # new flag
      - --concierge-namespace=concierge
      - --concierge-authenticator-name=my-webhook-authenticator
      - --concierge-authenticator-type=webhook
      - --token-env=MY_TOKEN
      command: /usr/local/bin/pinniped
      env: []
      provideClusterInfo: true```
```

This would output an ExecCredential like:
```json
{
  "kind": "ExecCredential",
  "apiVersion": "client.authentication.k8s.io/v1beta1",
  "spec": {},
  "status": {
    "token": "[base64 encoded, json encoded TokenCredentialRequest]"
  }
}
```

The embedded `status.token` field should be encoded in the format that the impersonation proxy expects.
