### ISSUE TITLE
Add basic LDAPIdentityProvider support

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#440]
```gherkin
Scenario as a cluster administrator, I can set up an LDAP identity provider so that my users can login using LDAP
Given I have the supervisor installed and running
  And I have a FederationDomain configured for the supervisor
  And I have a cluster running the concierge and configured to authenticate via the supervisor
  And I have an LDAP database running and accessible over "ldaps://" with no custom CA
  And I have a user account in the LDAP database
  And I have a service account with bind access in the LDAP database
Then I can create an LDAPIdentityProvider object in the supervisor namespace
  And I can create a Secret of type `kubernetes.io/basic-auth` with service account credentials.
And when I run "pinniped login oidc [...]" (with new flags)
 Then I see a username/password prompt
 And when I enter the correct username and password
 Then I see a JWT token response with my LDAP identity encoded in the `username` claim.
```

## LDAPIdentityProvider CRD Example

```yaml
kind: LDAPIdentityProvider
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
metadata:
  name: test-upstream-ldap-idp
  namespace: supervisor
spec:
  host: ldap.tools.svc.cluster.local
  tls:
    certificateAuthorityData: LS0tLS1CRUd[...]0tLQo=
  bind:
    secretName: test-ldap-service-account
  userSearch:
    base: ou=users,dc=pinniped,dc=dev
    filter: "mail={}"
    attributes:
      uid: uidNumber
      username: mail
```

### Notes

Basic user login with basic LDAP connection. Connect with ldaps://, with or without custom CA, authenticate using the provided service account credentials, and perform the user search and bind. No group search. Only support CLI-based username/password prompt. Only support those fields of LDAPIdentityProvider which are required for this basic first story.

More design notes in [HackMD](https://hackmd.io/SHPgH-1GQD6SAP4qWSTOLQ).

CLI command syntax and CRD API should be considered a rough sketch.

**Comment by enj** [comment]
```
And I can create a Secret of type `secrets.pinniped.dev/ldap-service-account` with service account credentials.
```

This secret type looks odd in regards to API group suffix.  It would be really weird to create:

```yaml
apiVersion: idp.supervisor.walrus.tld/v1alpha1
kind: LDAPIdentityProvider
...
```

but still have to link it to a `secrets.pinniped.dev/ldap-service-account`.  Both of these are part of our user facing API surface, and I think they should be consistent.

**Comment by cfryanr** [comment]
Hmm, I don't feel like would be weird for an idp.supervisor.walrus.tld.LDAPIdentityProvider to have a secretRef to a Secret of type `secrets.pinniped.dev/ldap-service-account`, the same way that it wouldn't be weird for it to have a secretRef to a Secret of type `kubernetes.io/basic-auth`. Seems normal that the data format of the Secret can come from a different project.

Since the service account is just a username and password, maybe we should use `kubernetes.io/basic-auth` instead of inventing our own in this case?

In regard to the CRD, maybe we want to create some nesting to make it easier to group similar settings together? There will be several settings about how to connect to the server, several settings about how to search for users, and several settings about how to search for groups. Should we group each under a top-level key, e.g. `server.url`, `userSearch.searchBase`, `groupSearch...`, and `serviceAccount.secretName`?

**Comment by mattmoyer** [comment]
> Since the service account is just a username and password, maybe we should use kubernetes.io/basic-auth instead of inventing our own in this case?

This sounds good to me.

> In regard to the CRD, maybe we want to create some nesting to make it easier to group similar settings together? 

This sounds good to me as well, maybe something like this?

```
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: LDAPIdentityProvider
metadata:
  name: my-ldap-identity-provider
spec:
  # where to connect
  endpoint: ldaps://my-server.example.com

  # how to authenticate to the server
  serviceAccount:
    secretName: my-ldap-service-account-secret

  # how to search for and parse user records
  users:
    base:  dc=test,dc=com
    usernameAttribute: cn

  # future: how to search for and parse group records
  groups:
    # TODO later

  # future: add TLS section for configuring custom CA, mTLS, and startTLS/LDAPS/... config
  tls:
    certificateAuthorityData: [...]
    # TODO later
```
