### ISSUE TITLE
Add `pinniped whoami` CLI command

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#444]
**Is your feature request related to a problem? Please describe.**

#439 added the `WhoAmIRequest` API.  We should have a CLI command to make that API easier to use.

**Describe the solution you'd like**

```shell
pinniped whoami
```

```
Current cluster info:

Name: foo
URL: https://example.com:8443

Current user info:

Username: kubernetes-admin
Groups: system:masters, system:authenticated
```

```shell
pinniped whoami -o yaml
```

```yaml
apiVersion: identity.concierge.pinniped.dev/v1alpha1
kind: WhoAmIRequest
metadata:
  creationTimestamp: null
spec: {}
status:
  kubernetesUserInfo:
    user:
      groups:
      - system:masters
      - system:authenticated
      username: kubernetes-admin
```

**Describe alternatives you've considered**

N/A

**Are you considering submitting a PR for this feature?**

N/A

- **How will this project improvement be tested?**

We would run the new CLI command in an integration test.

- **How does this change the current architecture?**

N/A

- **How will this change be backwards compatible?**

N/A

- **How will this feature be documented?**

Probably worth calling it out in docs as a way to confirm that authn is correctly configured.

**Additional context**

Not sure how we want to handle API group suffix in regards to this.
