### ISSUE TITLE
Deprecate CredentialIssuer status.kubeConfigInfo field and move strategy metadata into the strategies array

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#461]
In the Pinniped Concierge, the discovered API endpoint and CA certificate are currently published in the `status.kubeConfigInfo` field of the CredentialIssuer API:

```go
// Status of a credential issuer.
type CredentialIssuerStatus struct {
	// List of integration strategies that were attempted by Pinniped.
	Strategies []CredentialIssuerStrategy `json:"strategies"`

	// Information needed to form a valid Pinniped-based kubeconfig using the TokenCredentialRequest API.
	// +optional
	KubeConfigInfo *CredentialIssuerKubeConfigInfo `json:"kubeConfigInfo,omitempty"`

	// Information needed to form a valid Pinniped-based kubeconfig using the impersonation proxy.
	// +optional
	ImpersonationProxyInfo *CredentialIssuerImpersonationProxyInfo `json:"impersonationProxyInfo,omitempty"`
}

// Information needed to connect to the TokenCredentialRequest API on this cluster.
type CredentialIssuerKubeConfigInfo struct {
	// The Kubernetes API server URL.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Pattern=`^https://|^http://`
	Server string `json:"server"`

	// The Kubernetes API server CA bundle.
	// +kubebuilder:validation:MinLength=1
	CertificateAuthorityData string `json:"certificateAuthorityData"`
}
```

The name is confusing now that we've added the impersonation proxy strategy, since `kubeConfigInfo` only describes how to use the TokenCredentialRequest API, not actually how to connect to the cluster (which is in `status.impersonationProxyInfo` in those cases).

Instead, we want to move this data into a "tagged union" field nested under the CredentialIssuerStrategy object:

```go
// Status of an integration strategy that was attempted by Pinniped.
type CredentialIssuerStrategy struct {
	// Type of integration attempted.
	Type StrategyType `json:"type"`

	// Status of the attempted integration strategy.
	Status StrategyStatus `json:"status"`

	// Reason for the current status.
	Reason StrategyReason `json:"reason"`

	// Human-readable description of the current status.
	// +kubebuilder:validation:MinLength=1
	Message string `json:"message"`

	// When the status was last checked.
	LastUpdateTime metav1.Time `json:"lastUpdateTime"`

	// (new field below)

	// Frontend describes how clients can connect using this strategy.
	Frontend *CredentialIssuerFrontend `json:"frontend,omitempty"`
}

type CredentialIssuerFrontend struct {
	// Type describes which frontend mechanism clients can use with a strategy.
	Type FrontendType `json:"type"`

	// TokenCredentialRequestAPIInfo describes the parameters for the TokenCredentialRequest API on this Concierge.
	// This field is only set when Type is "TokenCredentialRequestAPI".
	TokenCredentialRequestAPIInfo *TokenCredentialRequestAPIInfo `json:"tokenCredentialRequestInfo,omitempty"`
}

type TokenCredentialRequestAPIInfo struct {
	// The Kubernetes API server URL.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:Pattern=`^https://|^http://`
	Server string `json:"server"`

	// The Kubernetes API server CA bundle.
	// +kubebuilder:validation:MinLength=1
	CertificateAuthorityData string `json:"certificateAuthorityData"`
}
```

In YAML form, it will look something like:
```yaml
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: pinniped-concierge-config
status:
  strategies:
  - type: KubeClusterSigningCertificate
    status: Success
    reason: FetchedKey
    message: Key was fetched successfully
    lastUpdateTime: "2021-03-02T15:35:20Z"
    frontend:
      type: TokenCredentialRequestAPI
      tokenCredentialRequestInfo:
        certificateAuthorityData: LS0tL[...]
        server: https://pinniped-control-plane:6443
```

This structure allows us to have several strategies that all use the same frontend mechanism. A client would process this:
- Loop over each strategy with status "Success"
- Look at the frontend and if it's a known type, use it.

This means that the server can express some preference for which strategy is preferred, and clients can automatically support new strategies as long as they use an existing frontend mechanism.

### Rollout

- In v0.7.0:
  - Introduce new fields
  - Deprecate the `status.kubeConfigInfo` field (but keep populating it).
- In v0.8.0:
  - Remove the  `status.kubeConfigInfo` field.

### Other Ideas

We have longer-term plans to perhaps move this data into the authenticator CRD's, but that's not in scope for this issue. We might also reorganize how the data is structured (see the [design doc](https://hackmd.io/X83kynapQgCJm_sDxXLCxg?view#Examples) for notes).
