### ISSUE TITLE
Add specific support for AD with a new ActiveDirectoryIdentityProvider API

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#593]
```gherkin
Scenario: as a cluster administrator, integrate with Active Directory
Given I have an Active Directory deployment
   And I have the Supervisor installed on a cluster
   And I have the Concierge installed on a cluster
When I create an ActiveDirectoryIdentityProvider CRD referencing my AD deployment
    And I generate a kubeconfig
 Then I can log in with my AD username and password
```

### Notes

Once we have initial working LDAP support, we should define an Active Directory CRD that looks exactly like LDAP minus the `LDAPIdentityProviderUserSearch` bits.  Internally, the code should be identical to generic LDAP (with some binary attribute handling), just with a very curated config.  Over time we will expand the functionality this CRD will provide (i.e. nested group search).  The main reasons for doing this now is to prevent future migrations across IDP types and to make the common config path dead simple.

### API

```yaml
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: ActiveDirectoryIdentityProvider
metadata:
  name: my-directory
spec:

  # Specify the host of the AD.
  host: "my-ad.example.com"

  # Specify the CA certificate of the LDAP server as a
  # base64-encoded PEM bundle.
  tls:
    certificateAuthorityData: "[...]"

  # hypothesis: none of the other user/group search/filter fields are needed for AD, since we can default them all safely

  # Specify the name of the Kubernetes Secret that contains your AD
  # bind account credentials. This service account will be used by the
  # Supervisor to perform user and group searches on the LDAP server.
  bind:
    secretName: openldap-bind-account
```
