### ISSUE TITLE
OIDCIdentityProvider with a "/" at the end of the issuer URL leads to errors

### ISSUE THREAD

**Issue by papivot** [vmware-tanzu/pinniped#600]
**What happened?**
```
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  namespace: pinniped-supervisor
  name: okta
spec:
  issuer: https://dev-xxxxxxx.okta.com/
  claims:
    username: nickname
    groups: groups
  client:
    secretName: okta-client-credentials
```
failed to validate configuration 
```
Status:
  Conditions:
    Last Transition Time:  2021-05-06T14:48:45Z
    Message:               loaded client credentials
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Type:                  ClientCredentialsValid
    Last Transition Time:  2021-05-06T14:48:45Z
    Message:               failed to perform OIDC discovery against "https://dev-xxxxxxx.okta.com/"
    Observed Generation:   1
    Reason:                Unreachable
    Status:                False
    Type:                  OIDCDiscoverySucceeded
  Phase:                   Error

 Error logged in pod - 

E0506 14:50:09.323065       1 upstreamwatcher.go:195] upstream-observer "msg"="found failing condition" "error"="OIDCIdentityProvider has a failing condition" "message"="failed to perform OIDC discovery against \"https://dev-xxxxxxxx.okta.com/\"" "name"="okta" "namespace"="pinniped-supervisor" "reason"="Unreachable" "type"="OIDCDiscoverySucceeded"
```

meanwhile 
```
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  namespace: pinniped-supervisor
  name: okta
spec:
  issuer: https://dev-xxxxxxxx.okta.com
  claims:
    username: nickname
    groups: groups
  client:
    secretName: okta-client-credentials
```
worked. 

```
Status:
  Conditions:
    Last Transition Time:  2021-05-06T14:28:52Z
    Message:               loaded client credentials
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Type:                  ClientCredentialsValid
    Last Transition Time:  2021-05-06T14:28:52Z
    Message:               discovered issuer configuration
    Observed Generation:   1
    Reason:                Success
    Status:                True
    Type:                  OIDCDiscoverySucceeded
  Phase:                   Ready
Events:                    <none>
```
> Please be specific and include screenshots and logs!

**What did you expect to happen?**

> Please be specific and include proposed behavior!

**What is the simplest way to reproduce this behavior?**

**In what environment did you see this bug?**
- Pinniped server version: 0.7.0
- Pinniped client version:
- Pinniped container image (if using a public container image):
- Pinniped configuration (what IDP(s) are you using? what downstream credential minting mechanisms are you using?): Okta
- Kubernetes version (use `kubectl version`): 1.18
- Kubernetes installer & version (e.g., `kubeadm version`): TKG
- Cloud provider or hardware configuration: vSphere 7
- OS (e.g: `cat /etc/os-release`): PhotonOS
- Kernel (e.g. `uname -a`):
- Others:

**What else is there to know about this bug?**
