### ISSUE TITLE
CredentialIssuer in v0.9.0 installation manifest is malformed.

### ISSUE THREAD

**Issue by mattmoyer** [vmware-tanzu/pinniped#659]
In the [v0.9.0 release YAML for installing the Concierge](https://github.com/vmware-tanzu/pinniped/releases/download/v0.9.0/install-pinniped-concierge.yaml), the `spec.impersonationProxy.service.type` flag is mistakenly named `mode` instead of `type`:

```yaml
apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: pinniped-concierge-config
  labels:
    app: pinniped-concierge
spec:
  impersonationProxy:
    mode: auto
    service:
      mode: LoadBalancer # should be `type: LoadBalancer`
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
```

The impact of this is minor, because the unknown field is ignored and the `type` field defaults to `LoadBalancer` anyway. However, it's pretty confusing and should be simple to fix.

Thanks to @jeuniii for noticing this and reporting it.
