### ISSUE TITLE
CI audit logging is insuffcient

### ISSUE THREAD

**Issue by enj** [vmware-tanzu/pinniped#807]
CI audit logging should capture full body of all pinniped CR instances and should capture all non-secret mutations caused by the pinniped controllers.

We currently only record metadata which makes it hard to debug certain failures:

```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
- "RequestReceived"
rules:
# Don't log requests for events
- level: None
  resources:
  - group: ""
    resources: ["events"]
# Don't log authenticated requests to certain non-resource URL paths.
- level: None
  userGroups: ["system:authenticated", "system:unauthenticated"]
  nonResourceURLs:
  - "/api*" # Wildcard matching.
  - "/version"
  - "/healthz"
  - "/readyz"
# A catch-all rule to log all other requests at the Metadata level.
- level: Metadata
  # Long-running requests like watches that fall under this rule will not
  # generate an audit event in RequestReceived.
  omitStages:
  - "RequestReceived"
```

xref: #348 #806
